### ISSUE TITLE
关于采用库上的一些建议

### ISSUE THREAD

**Issue by Seng-Jik** [MikiraSora/Wbooru#10]
1. WPF由于性能较差，且对触屏支持不完善，已经逐渐落后于现代Windows应用开发，为何不尝试跨平台且性能更好的WinUI 3或MAUI？
2. 如果需要对大量图源支持，何不考虑使用.NET 6/.NET Standard 2.0平台的F#语言编写[QwQ](https://github.com/Seng-Jik/QwQ)，它计划中将会尽可能支持更多的图源、漫画源，以统一的抽象层API访问这些内容，且具有较好的可扩展性，同时在抽象层充分考虑了性能与可容错性，并且对大部分图源做了完全测试（https://github.com/Seng-Jik/QwQ/actions/workflows/full-test.yml）。

**Comment by MikiraSora** [comment]
1.这玩意一开始就是我学WPF和C#相关技术练手用的，只不过我是真的在用而继续折腾维护。
2.目前没精力去接触F#以及相关GUI开发.
