### ISSUE TITLE
Unable to compile on Visual Studio 2019

### ISSUE THREAD

**Issue by Kashouryo** [MikiraSora/Wbooru#6]
When I tried to compile the newest master branch, Visual Studio threw a LoadingIndicator not found error in the WPF designer.

I can resolve this issue by renaming TargetFrameworks under the project's .csproj from net47 to net472.

**Comment by MikiraSora** [comment]
检查一下你是否clone的时候有没有递归下了依赖的repo
我这没法复现
或者你可以试一下找出原因，然后PR（

**Comment by Kashouryo** [comment]
Probably because I am lacking some dependencies. On my computer, I only have dotnet framework 4.7.2 SDK installed (not 4.7)
